version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ow5m9gfqgzpm"
s3_prefix = "hello-world-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
